default_platform(:ios)

platform :ios do

  lane :beta do |options|
    # Use fastlane match to fetch certificates and provisioning profiles
    match(
      type: "adhoc", 
      username: ENV['FASTLANE_USER'], # Ensure this is set correctly
      app_identifier: "com.benhamid.LMSCICD", 
      api_key: {
        key_id: ENV['FASTLANE_API_KEY_ID'],
        issuer_id: ENV['FASTLANE_API_ISSUER_ID'],
        key: ENV['FASTLANE_API_KEY']
      },
      git_url: ENV['MATCH_GIT_URL'],
      keychain_password: ENV['KEYCHAIN_PASSWORD']
    ) # This will pull certificates and provisioning profiles

    gym(
      export_xcargs: "-allowProvisioningUpdates", 
      configuration: "CD Staging Release", 
      silent: true, 
      suppress_xcode_output: false, 
      export_method: "ad-hoc"
    )

    ipa_path = Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]

    # Upload to TestApp.io
    sh <<-EOF
      curl -X POST https://upload.testapp.io/api/apps/9QorGVmE7M/builds \
        -H "Authorization: Bearer #{ENV['TESTAPP_API_KEY']}" \
        -F "file=@#{ipa_path}" \
        -F "release_notes=Uploaded automatically via Fastlane 🎉"
    EOF
  end
end
