default_platform(:ios)

platform :ios do
  lane :beta do |options|
    match(
      type: "adhoc", 
      username: ENV['FASTLANE_USER'], 
      app_identifier: "com.benhamid.LMSCICD", 
      api_key: {
        key_id: ENV['FASTLANE_API_KEY_ID'],
        issuer_id: ENV['FASTLANE_API_ISSUER_ID'],
        key: ENV['FASTLANE_API_KEY']
      },
      git_url: ENV['MATCH_GIT_URL'],
      git_branch: "main",  # Use the 'main' branch instead of 'master'
      readonly: false,
      force_for_new_devices: true
    )

    gym(export_xcargs: "-allowProvisioningUpdates", export_method: "ad-hoc")
    ipa_path = Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]

    # Upload to TestApp.io
    sh <<-EOF
      curl -X POST https://upload.testapp.io/api/apps/9QorGVmE7M/builds \
        -H "Authorization: Bearer #{ENV['TESTAPP_API_KEY']}" \
        -F "file=@#{ipa_path}" \
        -F "release_notes=Uploaded automatically via Fastlane 🎉"
    EOF
  end
end
